
#include "bsp_led.h"

void DEBUG_LED_Config(void)
{
	GPIO_InitTypeDef GPIO_InitStruct = {0};
	
	DEBUG_LED_CLK_ENABLE();
	
	GPIO_InitStruct.Pin = DEBUG_LED_GPIO_PIN;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(DEBUG_LED_GPIO_PORT, &GPIO_InitStruct);
	
	HAL_GPIO_WritePin(DEBUG_LED_GPIO_PORT, DEBUG_LED_GPIO_PIN, GPIO_PIN_RESET);
}

void DEBUG_LED_ON(void)
{
	HAL_GPIO_WritePin(DEBUG_LED_GPIO_PORT, DEBUG_LED_GPIO_PIN, GPIO_PIN_SET);
}

void DEBUG_LED_OFF(void)
{
	HAL_GPIO_WritePin(DEBUG_LED_GPIO_PORT, DEBUG_LED_GPIO_PIN, GPIO_PIN_RESET);
}

void DEBUG_LED_TOGGLE(void)
{
	HAL_GPIO_TogglePin(DEBUG_LED_GPIO_PORT,DEBUG_LED_GPIO_PIN);
}
